name: MEAN Stack CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t amit719/mean-backend ./backend
          docker push amit719/mean-backend
        working-directory: ./mean-stack-assignment/crud-dd-task-mean-app/crud-dd-task-mean-app

      - name: Build & Push Frontend
        run: |
          docker build -t amit719/mean-frontend ./frontend
          docker push amit719/mean-frontend
        working-directory: ./mean-stack-assignment/crud-dd-task-mean-app/crud-dd-task-mean-app

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/mean-stack-assignment/crud-dd-task-mean-app/crud-dd-task-mean-app
            sudo docker compose pull
            sudo docker compose up -d --build
